---
# file: handlers/main.yml
#

- name: restart prometheus
  service: name=prometheus state=restarted enabled=yes
  when: prometheus_use_service|bool

- name: reload prometheus
  service: name=prometheus state=reloaded
  when: prometheus_use_service|bool

- name: stop prometheus
  service: name=prometheus state=stopped
  when: prometheus_use_service|bool

- name: restart grafana
  service: name=grafana-server state=restarted enabled=yes

- name: restart node_exporter
  service: name=node_exporter state=restarted enabled=yes

- name: reload node_exporter
  service: name=node_exporter state=reloaded

- name: stop node_exporter
  service: name=node_exporter state=stopped

- name: restart jmx_exporter
  service: name=jmx_exporter state=restarted enabled=yes

- name: reload jmx_exporter
  service: name=jmx_exporter state=reloaded

- name: stop jmx_exporter
  service: name=jmx_exporter state=stopped

- name: restart alertmanager
  service: name=alertmanager state=restarted enabled=yes
  when: prometheus_use_service|bool

- name: reload alertmanager
  service: name=alertmanager state=reloaded
  when: prometheus_use_service|bool

- name: stop alertmanager
  service: name=alertmanager state=stopped
  when: prometheus_use_service|bool
